In [4]:
import pandas as pd
import base64
import io
import json

In [2]:
list = [1,2]

In [3]:
[{
        'if': { 'column_id': i },
        'background_color': '#D2F3FF'
    } for i in list]

[{'if': {'column_id': 1}, 'background_color': '#D2F3FF'},
 {'if': {'column_id': 2}, 'background_color': '#D2F3FF'}]

In [6]:
df = pd.read_csv("parsed_data.csv")

In [3]:
#df.columns.values.tolist()[1:]

In [18]:
list(df.columns.values)

TypeError: 'list' object is not callable

In [129]:
fp = os.getcwd()+'\\input_data\\'

In [ ]:
file = os.getcwd()+'\\input_data\\' + str(file_name)

In [141]:
file = os.getcwd()+'\\input_data\\' + str('parsed_data_2020_04_27_11_00.json')
file

'C:\\Users\\slabbegp\\Documents\\Personal\\7_Professional\\Masters_Control\\Dash_development\\input_data\\parsed_data_2020_04_27_11_00.json'

In [143]:
df = pd.read_json(file)
df

,Date,E3SC2001.PIDA.PV,E3SC2002.PIDA.PV,E3SC2003.PIDA.PV,e3pi1505.DACA.PV,E3LC2003.PIDA.PV,E3TC2092.PIDA.PV,E3TC2093.PIDA.PV,E3PC2079.PIDA.PV,E3FC2031.PIDA.OP,...,E3PC2073.PIDA.PV,E3SC2002.PIDA.SP,E3SC2002.PIDA.OP,e3fc2004a.PIDA.PV,E3FY2003Y.AUTOMANA.OPEU,E3FY2003Y.OVRDSELA.OPEU,E3PY2077A.AUTOMANA.OP,E3PY2077B.AUTOMANA.OP,e3fc2004a.PIDA.SP,e3fc2004a.PIDA.OP
0,2019-06-17 22:30:55,21.14,21.45,21.64,4143.68,52.13,76.29,81.73,-0.22,28.19,...,2.16,21.40,34.61,580.12,526.94,521.27,29.83,29.83,581.20,67.53
1,2019-06-17 22:31:00,21.16,21.38,21.64,4142.59,51.97,76.29,81.72,-0.22,28.19,...,2.16,21.19,34.19,576.99,523.87,521.53,29.84,29.84,581.57,67.70
10,2019-06-17 22:31:45,21.25,21.24,21.61,4141.66,51.26,76.14,81.57,-0.21,28.40,...,2.14,21.20,34.34,600.47,524.78,520.90,29.83,29.83,594.86,68.07
100,2019-06-17 22:39:15,21.66,21.80,21.92,4132.08,48.89,74.76,81.27,-0.22,28.14,...,2.14,21.66,35.70,606.15,536.08,526.71,30.08,30.08,603.35,68.45
1000,2019-06-17 23:54:15,21.59,21.60,21.87,4134.02,48.23,76.74,82.80,-0.20,29.24,...,2.09,21.72,36.01,603.41,530.55,528.46,30.14,30.14,606.78,69.18
1001,2019-06-17 23:54:20,21.54,21.63,21.90,4133.95,48.65,76.75,82.78,-0.20,29.30,...,2.09,21.78,36.24,607.19,531.71,527.98,30.14,30.14,610.23,69.24
1002,2019-06-17 23:54:25,21.50,21.71,21.92,4135.27,49.09,76.75,82.79,-0.20,29.21,...,2.09,21.73,36.20,608.92,534.57,526.75,30.14,30.14,610.10,69.19
1003,2019-06-17 23:54:30,21.50,21.78,21.93,4136.21,48.74,76.59,82.78,-0.20,29.10,...,2.08,21.77,36.11,610.23,533.61,525.74,30.14,30.14,606.45,69.04
1004,2019-06-17 23:54:35,21.50,21.79,21.96,4135.27,48.59,76.58,82.79,-0.19,28.85,...,2.09,21.62,35.83,610.38,529.05,525.67,30.15,30.15,609.49,69.11
1005,2019-06-17 23:54:40,21.50,21.79,21.95,4135.82,48.99,76.59,82.80,-0.19,28.71,...,2.10,21.64,35.70,608.77,531.81,526.44,30.14,30.14,609.87,69.17
1006,2019-06-17 23:54:45,21.53,21.76,21.94,4134.18,49.84,76.59,82.79,-0.19,28.58,...,2.10,21.75,35.82,611.00,532.72,526.90,30.13,30.13,610.61,69.16
1007,2019-06-17 23:54:50,21.54,21.74,21.95,4136.21,50.66,76.60,82.80,-0.19,28.57,...,2.10,21.64,35.72,610.74,535.80,526.93,30.11,30.11,603.97,68.85
1008,2019-06-17 23:54:55,21.51,21.74,21.96,4136.28,50.27,76.61,82.80,-0.19,28.58,...,2.10,21.57,35.43,611.77,535.44,526.75,30.10,30.10,597.96,68.48
1009,2019-06-17 23:55:00,21.53,21.75,21.96,4135.74,49.60,76.60,82.80,-0.19,28.63,...,2.10,21.57,35.29,609.21,532.12,526.53,30.08,30.08,602.25,68.57
101,2019-06-17 22:39:20,21.63,21.77,21.97,4132.93,49.57,74.76,81.27,-0.22,28.28,...,2.14,21.37,35.10,602.35,533.63,525.81,30.05,30.05,600.67,68.48
1010,2019-06-17 23:55:05,21.53,21.71,21.93,4137.30,49.44,76.59,82.78,-0.19,28.75,...,2.10,21.47,34.89,605.32,531.37,526.38,30.06,30.06,604.17,68.67
1011,2019-06-17 23:55:10,21.54,21.59,21.87,4136.83,49.66,76.58,82.80,-0.19,28.77,...,2.10,21.64,35.21,602.28,533.63,525.89,30.04,30.04,601.80,68.66
1012,2019-06-17 23:55:15,21.58,21.50,21.85,4138.78,49.61,76.60,82.80,-0.19,28.79,...,2.11,21.55,35.17,600.88,533.97,525.24,30.01,30.01,604.10,68.80
1013,2019-06-17 23:55:20,21.53,21.51,21.85,4141.19,49.02,76.59,82.79,-0.20,28.98,...,2.11,21.39,34.92,601.20,535.32,524.23,29.99,29.99,606.09,68.95
1014,2019-06-17 23:55:25,21.46,21.48,21.88,4139.01,48.71,76.59,82.79,-0.20,28.91,...,2.12,21.42,34.91,602.87,530.00,523.47,29.97,29.97,608.22,69.10
1015,2019-06-17 23:55:30,21.37,21.48,21.83,4139.94,49.10,76.59,82.64,-0.20,28.83,...,2.12,21.50,34.96,605.15,531.79,523.65,29.95,29.95,613.21,69.30
1016,2019-06-17 23:55:35,21.31,21.49,21.76,4140.96,49.20,76.59,82.64,-0.20,28.71,...,2.13,21.37,34.68,609.17,532.44,523.14,29.94,29.94,611.01,69.18
1017,2019-06-17 23:55:40,21.27,21.49,21.70,4143.22,48.81,76.60,82.64,-0.20,28.72,...,2.13,21.28,34.47,611.07,528.48,522.60,29.91,29.91,611.07,69.18
1018,2019-06-17 23:55:45,21.23,21.44,21.69,4143.45,49.11,76.59,82.64,-0.21,28.61,...,2.14,21.41,34.55,614.80,531.21,521.70,29.88,29.88,617.78,69.28
1019,2019-06-17 23:55:50,21.23,21.37,21.69,4144.85,49.08,76.60,82.64,-0.21,28.60,...,2.14,21.24,34.32,613.33,530.90,520.70,29.86,29.86,613.90,69.22
102,2019-06-17 22:39:25,21.50,21.71,21.95,4132.62,49.78,74.77,81.26,-0.22,28.15,...,2.15,21.52,35.02,602.36,533.65,525.85,30.03,30.03,602.83,68.56
1020,2019-06-17 23:55:55,21.19,21.32,21.69,4145.63,49.04,76.59,82.64,-0.21,28.51,...,2.15,21.40,34.57,612.43,531.81,519.78,29.84,29.84,614.77,69.33
1021,2019-06-17 23:56:00,21.07,21.31,21.70,4147.42,49.38,76.60,82.49,-0.21,28.52,...,2.15,21.07,33.97,611.42,530.87,519.23,29.82,29.82,612.99,69.35
1022,2019-06-17 23:56:05,20.98,21.27,21.74,4148.51,49.77,76.58,82.49,-0.21,28.67,...,2.16,20.98,33.62,610.79,534.23,519.04,29.79,29.79,613.04,69.44
1023,2019-06-17 23:56:10,20.95,21.21,21.67,4148.67,49.66,76.60,82.49,-0.21,28.71,...,2.16,21.00,33.46,612.61,532.99,518.89,29.78,29.78,612.67,69.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
972,2019-06-17 23:51:55,21.50,21.64,21.86,4133.95,52.85,76.75,82.64,-0.24,28.88,...,2.27,21.71,35.89,591.73,532.97,526.83,29.83,29.83,585.00,67.94
973,2019-06-17 23:52:00,21.46,21.66,21.87,4134.49,51.96,76.74,82.80,-0.24,28.81,...,2.27,21.65,35.77,589.13,532.68,527.01,29.86,29.86,585.77,67.97
974,2019-06-17 23:52:05,21.40,21.71,21.87,4134.02,51.00,76.74,82.78,-0.23,28.60,...,2.28,21.70,35.80,586.65,530.60,526.74,29.88,29.88,585.44,68.02
975,2019-06-17 23:52:10,21.38,21.70,21.88,4131.30,51.58,76.80,82.80,-0.22,28.53,...,2.28,21.58,35.55,582.78,531.81,527.05,29.87,29.87,584.77,68.17
976,2019-06-17 23:52:15,21.45,21.69,21.88,4129.20,52.44,76.73,82.80,-0.22,28.64,...,2.28,21.69,35.74,582.30,531.30,528.20,29.85,29.85,583.99,68.20
977,2019-06-17 23:52:20,21.49,21.71,21.87,4130.68,52.59,76.89,82.79,-0.22,28.53,...,2.27,21.71,35.71,586.01,533.65,529.69,29.83,29.83,585.23,68.08
978,2019-06-17 23:52:25,21.53,21.68,21.86,4132.23,51.22,76.91,82.79,-0.22,28.53,...,2.27,21.73,35.86,588.12,531.55,529.99,29.81,29.81,587.71,68.04
979,2019-06-17 23:52:30,21.58,21.72,21.86,4133.56,50.64,76.75,82.79,-0.22,28.58,...,2.26,21.89,36.14,588.39,532.44,528.87,29.79,29.79,590.91,68.11
98,2019-06-17 22:39:05,21.40,21.74,21.94,4128.42,48.30,74.76,81.27,-0.22,28.12,...,2.13,21.66,35.94,609.06,536.40,529.60,30.12,30.12,604.27,68.54
980,2019-06-17 23:52:35,21.57,21.68,21.86,4133.40,51.17,76.76,82.81,-0.22,28.91,...,2.26,21.62,35.86,588.90,530.89,527.56,29.77,29.77,584.86,67.89
981,2019-06-17 23:52:40,21.53,21.72,21.87,4132.70,51.67,76.74,82.78,-0.22,28.93,...,2.26,21.75,36.02,585.91,532.76,527.13,29.77,29.77,585.96,67.97
982,2019-06-17 23:52:45,21.48,21.75,21.88,4130.52,51.42,76.74,82.80,-0.21,29.30,...,2.26,21.46,35.45,584.47,534.87,527.08,29.76,29.76,586.57,68.06
983,2019-06-17 23:52:50,21.47,21.75,21.87,4132.31,50.82,76.74,82.78,-0.22,29.59,...,2.24,21.80,35.82,583.77,533.95,527.59,29.78,29.78,591.00,68.34
984,2019-06-17 23:52:55,21.51,21.73,21.84,4132.31,50.22,76.74,82.79,-0.22,29.52,...,2.24,21.84,35.97,585.71,532.76,527.74,29.82,29.82,592.05,68.42
985,2019-06-17 23:53:00,21.60,21.73,21.89,4131.22,49.76,76.74,82.80,-0.22,29.55,...,2.23,21.82,36.08,585.99,533.63,527.60,29.85,29.85,594.17,68.60
986,2019-06-17 23:53:05,21.63,21.73,22.00,4130.44,49.48,76.75,82.79,-0.22,29.64,...,2.22,21.77,36.04,591.37,531.83,527.83,29.90,29.90,594.48,68.51
987,2019-06-17 23:53:10,21.57,21.73,22.03,4129.51,49.32,76.75,82.79,-0.22,29.64,...,2.21,21.85,36.28,594.66,530.87,528.18,29.95,29.95,598.50,68.62
988,2019-06-17 23:53:15,21.50,21.77,22.05,4130.75,49.65,76.74,82.94,-0.22,29.42,...,2.20,21.88,36.40,598.05,530.01,527.93,30.01,30.01,598.60,68.53
989,2019-06-17 23:53:20,21.52,21.82,22.06,4132.47,49.50,76.73,82.95,-0.22,29.33,...,2.18,21.91,36.53,598.88,530.71,527.39,30.04,30.04,603.02,68.67
99,2019-06-17 22:39:10,21.48,21.76,21.94,4130.52,48.08,74.78,81.27,-0.22,28.14,...,2.14,21.67,35.86,609.31,532.76,528.26,30.10,30.10,604.79,68.45
990,2019-06-17 23:53:25,21.59,21.89,22.01,4133.71,49.87,76.74,82.96,-0.23,29.18,...,2.16,21.76,36.08,600.31,530.30,526.68,30.07,30.07,601.68,68.61
991,2019-06-17 23:53:30,21.73,21.88,21.96,4134.41,50.47,76.73,82.94,-0.22,28.97,...,2.15,21.73,35.93,597.32,530.87,525.87,30.09,30.09,598.67,68.60
992,2019-06-17 23:53:35,21.68,21.84,21.98,4132.70,50.91,76.59,82.94,-0.22,28.95,...,2.14,21.68,35.70,598.37,530.89,525.91,30.10,30.10,597.19,68.49
993,2019-06-17 23:53:40,21.63,21.76,21.95,4132.47,50.41,76.74,82.94,-0.22,28.84,...,2.13,21.52,35.38,598.12,531.26,527.15,30.13,30.13,594.67,68.34
994,2019-06-17 23:53:45,21.54,21.70,21.93,4132.39,49.66,76.59,82.94,-0.22,28.71,...,2.12,21.66,35.58,596.54,528.15,527.92,30.14,30.14,594.52,68.32
995,2019-06-17 23:53:50,21.45,21.68,21.91,4133.17,49.22,76.62,82.95,-0.22,28.86,...,2.11,21.64,35.51,593.45,530.30,528.01,30.14,30.14,598.15,68.57
996,2019-06-17 23:53:55,21.42,21.66,21.88,4132.39,49.22,77.45,83.04,-0.21,28.91,...,2.11,21.73,35.69,593.05,527.54,528.55,30.14,30.14,596.14,68.60
997,2019-06-17 23:54:00,21.46,21.66,21.84,4132.93,49.44,76.74,82.94,-0.21,28.96,...,2.10,21.57,35.38,592.71,531.17,529.06,30.14,30.14,605.27,69.01
998,2019-06-17 23:54:05,21.52,21.68,21.85,4132.70,49.64,76.75,82.95,-0.21,29.01,...,2.10,21.83,35.74,593.09,530.25,529.17,30.14,30.14,600.34,69.03
999,2019-06-17 23:54:10,21.57,21.63,21.85,4132.78,49.02,76.73,82.94,-0.20,29.13,...,2.09,21.77,35.82,598.81,532.74,528.82,30.14,30.14,604.34,69.13

In [74]:
data=df.to_dict('rows')

In [83]:
[{'name': 'file names', 'id': 'file names'}],

([{'name': 'file names', 'id': 'file names'}],)

In [84]:
[{'name': 'file names', 'id': i} for i in list_of_files]

[{'name': 'file names', 'id': 'parsed_data - Copy.json'},
 {'name': 'file names', 'id': 'parsed_data.json'}]

In [93]:
df1 = pd.DataFrame(list_of_files,columns =['File names'])

In [92]:
[{'name': i, 'id': i} for i in df1.columns]

[{'name': 'File names', 'id': 'File names'}]

In [94]:
df1.to_dict('rows'),

([{'File names': 'parsed_data - Copy.json'},
  {'File names': 'parsed_data.json'}],)

In [113]:
path = os.getcwd()+'\\input_data\\'
path

'C:\\Users\\slabbegp\\Documents\\Personal\\7_Professional\\Masters_Control\\Dash_development\\input_data\\input_data\\'

In [120]:
import datetime
datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

'2020-04-27 09:44:19'

In [123]:
search_for_datafiles()

[]

In [126]:
os.chdir('..')

In [127]:
os.getcwd()

'C:\\Users\\slabbegp\\Documents\\Personal\\7_Professional\\Masters_Control\\Dash_development'

In [37]:
df = pd.read_json('parsed_data.json')

In [40]:
df=df.sort_index()

In [42]:
df = df.set_index(df.columns[0])

In [ ]:
import os

path = os.getcwd()

In [46]:
path

'C:\\Users\\slabbegp\\Documents\\Personal\\7_Professional\\Masters_Control\\Dash_development'

In [48]:
import os

path = os.getcwd()

files = []
# r=root, d=directories, f = files
for r, d, f in os.walk(path):
    for file in f:
        if '.json' in file:
            #files.append(os.path.join(r, file))
            files.append(file)

for f in files:
    print(f)

parsed_data.json

In [57]:
def search_for_datafiles():
    path = os.getcwd()

    files = []
    # r=root, d=directories, f = files
    for r, d, f in os.walk(path):
        for file in f:
            if '.json' in file:
                #files.append(os.path.join(r, file))
                files.append(file)
    
    return files

In [63]:
list_of_files = []

In [64]:
list_of_files = search_for_datafiles()

In [65]:
files = [{'label': i, 'value': i} for i in list_of_files]

In [66]:
files

[{'label': 'parsed_data - Copy.json', 'value': 'parsed_data - Copy.json'},
 {'label': 'parsed_data.json', 'value': 'parsed_data.json'}]

In [135]:
name = '{}.json'.format('test')
df.to_json(name)

In [77]:
[{'name': i, 'id': 'file names'} for i in list_of_files]

[{'name': 'parsed_data - Copy.json', 'id': 'file names'},
 {'name': 'parsed_data.json', 'id': 'file names'}]

In [4]:
df = pd.DataFrame([['a', 'b'], ['c', 'd']],
                  index=['row 1', 'row 2'],
                  columns=['col 1', 'col 2'])

In [5]:
df.to_json(orient='split')

'{"columns":["col 1","col 2"],"index":["row 1","row 2"],"data":[["a","b"],["c","d"]]}'

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/gapminderDataFiveYear.csv')

In [3]:
#df

In [6]:
filtered = df.query('country in "Albania"')

In [10]:
type(filtered.keys())

pandas.core.indexes.base.Index

In [9]:
filtered.keys().to_list()

['country', 'year', 'pop', 'continent', 'lifeExp', 'gdpPercap']

In [27]:
list(filtered.keys())

['country', 'year', 'pop', 'continent', 'lifeExp', 'gdpPercap']

In [15]:
test = filtered.to_dict('records')

In [135]:
data = pd.DataFrame()
data = data.from_dict(test, orient='columns')
#data = data.sort_index()

In [23]:
data.keys().to_list()

['continent', 'country', 'gdpPercap', 'lifeExp', 'pop', 'year']

In [136]:
data

   continent  country    gdpPercap  lifeExp        pop  year
0     Europe  Albania  1601.056136   55.230  1282697.0  1952
1     Europe  Albania  1942.284244   59.280  1476505.0  1957
2     Europe  Albania  2312.888958   64.820  1728137.0  1962
3     Europe  Albania  2760.196931   66.220  1984060.0  1967
4     Europe  Albania  3313.422188   67.690  2263554.0  1972
5     Europe  Albania  3533.003910   68.930  2509048.0  1977
6     Europe  Albania  3630.880722   70.420  2780097.0  1982
7     Europe  Albania  3738.932735   72.000  3075321.0  1987
8     Europe  Albania  2497.437901   71.581  3326498.0  1992
9     Europe  Albania  3193.054604   72.950  3428038.0  1997
10    Europe  Albania  4604.211737   75.651  3508512.0  2002
11    Europe  Albania  5937.029526   76.423  3600523.0  2007

In [57]:
data['{}'.format('country')]

0     Albania
1     Albania
2     Albania
3     Albania
4     Albania
5     Albania
6     Albania
7     Albania
8     Albania
9     Albania
10    Albania
11    Albania
Name: country, dtype: object

In [73]:
'{}:{}'.format("a",1)

'a:1'

In [89]:
test_df = test_df.append({
                        '{}'.format(data.keys().to_list()[2:])
                         
                        },ignore_index=True)

TypeError: cannot concatenate object of type "<class 'set'>"; only pd.Series, pd.DataFrame, and pd.Panel (deprecated) objs are valid

In [113]:
dict1 = {'property':'1','name':'test','surname':'test'}

In [118]:
dict1.append( {'property':'2','name' : 'gideon'} )

AttributeError: 'dict' object has no attribute 'append'

In [145]:
[(1,2)]

[(1, 2)]

In [143]:
labels = ['dd','value']
data1 = [2,1]
df = pd.DataFrame.from_records(data1, columns=labels)
df

TypeError: 'int' object is not iterable

In [137]:
data.keys().to_list()[2:]

['gdpPercap', 'lifeExp', 'pop', 'year']

In [151]:
import numpy as np

In [163]:
r = ['identifier']+['t','y']

r

['identifier', 't', 'y']

In [166]:
columns = ['param'] + data.keys().to_list()[2:]
max_list = ['Max']
min_list = ['Min']
median_list = ['Median']
mean_list = ['Mean']
std_list = ['StdDev']
nans = ['Nans']
for index_label in data.keys().to_list()[2:]:
    max_list.append(
                    np.nanmax(data['{}'.format(index_label)].to_list())
                   )
    min_list.append(
                np.nanmin(data['{}'.format(index_label)].to_list())
               )
    median_list.append(
                np.nanmedian(data['{}'.format(index_label)].to_list())
               )
    mean_list.append(
                np.nanmean(data['{}'.format(index_label)].to_list())
               )
    std_list.append(
                np.nanstd(data['{}'.format(index_label)].to_list())
               )
    nans.append(np.any(np.isnan(data['{}'.format(index_label)].to_list())))
                
max_list = [(max_list),(min_list),(median_list),(mean_list),(std_list),(nans)]
df = pd.DataFrame.from_records(max_list, columns=columns)
df

    param gdpPercap  lifeExp          pop     year
0     Max   5937.03   76.423  3.60052e+06     2007
1     Min   1601.06    55.23   1.2827e+06     1952
2  Median   3253.24   69.675  2.64457e+06   1979.5
3    Mean   3255.37  68.4329  2.58025e+06   1979.5
4  StdDev   1141.59  6.05373       793310  17.2603
5    Nans     False    False        False    False

In [167]:
df[1:]

    param gdpPercap  lifeExp          pop     year
1     Min   1601.06    55.23   1.2827e+06     1952
2  Median   3253.24   69.675  2.64457e+06   1979.5
3    Mean   3255.37  68.4329  2.58025e+06   1979.5
4  StdDev   1141.59  6.05373       793310  17.2603
5    Nans     False    False        False    False

In [86]:
data.keys().to_list()[2:]

['gdpPercap', 'lifeExp', 'pop', 'year']

In [33]:
list1 = ['continent', 'country']

In [34]:
len(list1)

2

In [45]:
#data[list1]

In [38]:
data.columns.values.tolist().index('continent')

0

In [42]:
new_list = []
for i in list1:
    new_list.append(data.columns.values.tolist().index(i))
new_list

[0, 1]

In [34]:
a = {}
type(a)

dict

In [36]:
len(test)

12

In [37]:
[{"label": i, "value": i} for i in [1,2]]

[{'label': 1, 'value': 1}, {'label': 2, 'value': 2}]

In [71]:
a = df.from_dict(filtered, orient='columns')

In [86]:
#a.sort_index()
a.columns.values.tolist().index('country')

0

In [77]:
a.set_index(df.columns['country'])#[lii]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [75]:
lii = ['year']

In [56]:
a[list].columns.values.tolist()

['country', 'year']

In [5]:
'yaxis{}'.format(1):dict(1)

SyntaxError: illegal target for annotation (<ipython-input-5-528d3870f0ab>, line 1)